### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by Hertzole** [MirageNet/SteamyFaceNG#9]
**Describe the bug**
When building a Linux build, it fails because the Steamworks API seems to be missing.

**To Reproduce**
1. Create a new project and import the SteamyFaceNG package.
2. Start building a Linux project
3. See error

**Expected behavior**
The build should succeed.

**Desktop (please complete the following information):**
* OS: Windws 10
* Build target: Linux standalone
* Unity version: 2020.3.14f1
* Mirage version: 99.0.2
* Steamy Face NG version: 4.0.0

**Comment by phodoval** [comment]
Fixed in 4.0.1.
